description: EUROPEAN UNION
urls:
- https://raw.githubusercontent.com/ipverse/country-ip-blocks/master/country/at/ipv4-aggregated.txt
- https://raw.githubusercontent.com/ipverse/country-ip-blocks/master/country/be/ipv4-aggregated.txt
- https://raw.githubusercontent.com/ipverse/country-ip-blocks/master/country/bg/ipv4-aggregated.txt
- https://raw.githubusercontent.com/ipverse/country-ip-blocks/master/country/hr/ipv4-aggregated.txt
- https://raw.githubusercontent.com/ipverse/country-ip-blocks/master/country/cy/ipv4-aggregated.txt
- https://raw.githubusercontent.com/ipverse/country-ip-blocks/master/country/cz/ipv4-aggregated.txt
- https://raw.githubusercontent.com/ipverse/country-ip-blocks/master/country/dk/ipv4-aggregated.txt
- https://raw.githubusercontent.com/ipverse/country-ip-blocks/master/country/ee/ipv4-aggregated.txt
- https://raw.githubusercontent.com/ipverse/country-ip-blocks/master/country/fi/ipv4-aggregated.txt
- https://raw.githubusercontent.com/ipverse/country-ip-blocks/master/country/fr/ipv4-aggregated.txt
- https://raw.githubusercontent.com/ipverse/country-ip-blocks/master/country/de/ipv4-aggregated.txt
- https://raw.githubusercontent.com/ipverse/country-ip-blocks/master/country/gr/ipv4-aggregated.txt
- https://raw.githubusercontent.com/ipverse/country-ip-blocks/master/country/hu/ipv4-aggregated.txt
- https://raw.githubusercontent.com/ipverse/country-ip-blocks/master/country/ie/ipv4-aggregated.txt
- https://raw.githubusercontent.com/ipverse/country-ip-blocks/master/country/it/ipv4-aggregated.txt
- https://raw.githubusercontent.com/ipverse/country-ip-blocks/master/country/lv/ipv4-aggregated.txt
- https://raw.githubusercontent.com/ipverse/country-ip-blocks/master/country/lt/ipv4-aggregated.txt
- https://raw.githubusercontent.com/ipverse/country-ip-blocks/master/country/lu/ipv4-aggregated.txt
- https://raw.githubusercontent.com/ipverse/country-ip-blocks/master/country/mt/ipv4-aggregated.txt
- https://raw.githubusercontent.com/ipverse/country-ip-blocks/master/country/nl/ipv4-aggregated.txt
- https://raw.githubusercontent.com/ipverse/country-ip-blocks/master/country/pl/ipv4-aggregated.txt
- https://raw.githubusercontent.com/ipverse/country-ip-blocks/master/country/pt/ipv4-aggregated.txt
- https://raw.githubusercontent.com/ipverse/country-ip-blocks/master/country/ro/ipv4-aggregated.txt
- https://raw.githubusercontent.com/ipverse/country-ip-blocks/master/country/sk/ipv4-aggregated.txt
- https://raw.githubusercontent.com/ipverse/country-ip-blocks/master/country/si/ipv4-aggregated.txt
- https://raw.githubusercontent.com/ipverse/country-ip-blocks/master/country/es/ipv4-aggregated.txt
- https://raw.githubusercontent.com/ipverse/country-ip-blocks/master/country/se/ipv4-aggregated.txt
# EAA
- https://raw.githubusercontent.com/ipverse/country-ip-blocks/master/country/gb/ipv4-aggregated.txt
- https://raw.githubusercontent.com/ipverse/country-ip-blocks/master/country/no/ipv4-aggregated.txt
- https://raw.githubusercontent.com/ipverse/country-ip-blocks/master/country/ch/ipv4-aggregated.txt
- https://raw.githubusercontent.com/ipverse/country-ip-blocks/master/country/is/ipv4-aggregated.txt
- https://raw.githubusercontent.com/ipverse/country-ip-blocks/master/country/li/ipv4-aggregated.txt

