description: FANG companies
urls:
  # FACEBOOK
  - https://raw.githubusercontent.com/ipverse/as-ip-blocks/master/as/32934/ipv4-aggregated.txt
  # AMAZON
  - https://raw.githubusercontent.com/ipverse/as-ip-blocks/master/as/16509/ipv4-aggregated.txt
  - https://raw.githubusercontent.com/ipverse/as-ip-blocks/master/as/14618/ipv4-aggregated.txt
  - https://raw.githubusercontent.com/ipverse/as-ip-blocks/master/as/8987/ipv4-aggregated.txt
  # NETFLIX
  - https://raw.githubusercontent.com/ipverse/as-ip-blocks/master/as/2906/ipv4-aggregated.txt
  - https://raw.githubusercontent.com/ipverse/as-ip-blocks/master/as/40027/ipv4-aggregated.txt
  # GOOGLE
  - https://raw.githubusercontent.com/ipverse/as-ip-blocks/master/as/15169/ipv4-aggregated.txt
  - https://raw.githubusercontent.com/ipverse/as-ip-blocks/master/as/16591/ipv4-aggregated.txt
  - https://raw.githubusercontent.com/ipverse/as-ip-blocks/master/as/396982/ipv4-aggregated.txt
  - https://raw.githubusercontent.com/ipverse/as-ip-blocks/master/as/394089/ipv4-aggregated.txt
  - https://raw.githubusercontent.com/ipverse/as-ip-blocks/master/as/19527/ipv4-aggregated.txt
  

