description: Akamai
urls:
  - https://raw.githubusercontent.com/ipverse/as-ip-blocks/master/as/16625/ipv4-aggregated.txt
  - https://raw.githubusercontent.com/ipverse/as-ip-blocks/master/as/20940/ipv4-aggregated.txt