description: Amazon
urls:
  - https://raw.githubusercontent.com/ipverse/as-ip-blocks/master/as/16509/ipv4-aggregated.txt
  - https://raw.githubusercontent.com/ipverse/as-ip-blocks/master/as/14618/ipv4-aggregated.txt
  - https://raw.githubusercontent.com/ipverse/as-ip-blocks/master/as/8987/ipv4-aggregated.txt
