description: Microsoft
urls:
  - https://raw.githubusercontent.com/ipverse/as-ip-blocks/master/as/8068/ipv4-aggregated.txt
  - https://raw.githubusercontent.com/ipverse/as-ip-blocks/master/as/8069/ipv4-aggregated.txt
  - https://raw.githubusercontent.com/ipverse/as-ip-blocks/master/as/8070/ipv4-aggregated.txt
  - https://raw.githubusercontent.com/ipverse/as-ip-blocks/master/as/8075/ipv4-aggregated.txt
  - https://raw.githubusercontent.com/ipverse/as-ip-blocks/master/as/3598/ipv4-aggregated.txt