description: Telegram
urls:
  - https://raw.githubusercontent.com/ipverse/as-ip-blocks/master/as/44907/ipv4-aggregated.txt
  - https://raw.githubusercontent.com/ipverse/as-ip-blocks/master/as/62041/ipv4-aggregated.txt